# Memory and GC allocation
org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+UseParallelGC -XX:+HeapDumpOnOutOfMemoryError

# Build speed optimizations
org.gradle.parallel=true
org.gradle.caching=true

# Android X support
android.useAndroidX=true
android.enableJetifier=true